.SILENT:

default:
	gcc -pthread -lrt SortedList.c lab2b.c -o lab2b

clean:
	rm -f lab2b

dist:
	tar -zcvf lab2b-704465898.tar.gz lab2b.c SortedList.h SortedList.c Makefile iterations.png threads.png README
